spring.application.name=auth-service
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=${JWT_SECRET_KEY:notifyhub_jwt_secret_key_that_is_long_enough_for_hs256_algorithm}
jwt.expiration.ms=${JWT_EXPIRATION_TIME:86400000}

# User Service URL
user.service.url=http://localhost:8082