server.port=8080
spring.application.name=api-gateway


# JWT
jwt.secret=${JWT_SECRET_KEY:notifyhub_jwt_secret_key_that_is_long_enough_for_hs256_algorithm}

#Eureka client registry
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true